import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load the results generated by Phase 1
file_name = "phase1_preprocessing_results.csv"
try:
    df = pd.read_csv(file_name)
except FileNotFoundError:
    print(f" Error: '{file_name}' not found. Make sure train_baseline.py finished successfully.")
    exit()

# 2. Set up the visual style
sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(1, 3, figsize=(18, 6))

# 3. Plot Training Error
sns.barplot(
    data=df, 
    x='preprocessing', 
    y='train_mse', 
    palette='Blues_d', 
    ax=axes[0]
)
axes[0].set_title('Training Error (MSE)', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Preprocessing Configuration', fontsize=12)
axes[0].set_ylabel('Train MSE', fontsize=12)

# 4. Plot Testing Error
sns.barplot(
    data=df, 
    x='preprocessing', 
    y='test_mse', 
    palette='Oranges_d', 
    ax=axes[1]
)
axes[1].set_title('Testing Error (True Generalization)', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Preprocessing Configuration', fontsize=12)
axes[1].set_ylabel('Test MSE', fontsize=12)

# 5. Plot Mean Absolute Error
sns.barplot(
    data=df, 
    x='preprocessing', 
    y='mae', 
    palette='Greens_d', 
    ax=axes[2]
)
axes[2].set_title('Mean Absolute Error (MAE)', fontsize=14, fontweight='bold')
axes[2].set_xlabel('Preprocessing Configuration', fontsize=12)
axes[2].set_ylabel('Test MAE', fontsize=12)
for ax in axes:
    ax.tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.savefig("phase1_results_plot.png", dpi=300, bbox_inches='tight')
print("Plot saved as 'phase1_results_plot.png'")
plt.show()
