import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Load the results generated by the GRU training script
file_name = "phase1_gru_results.csv"
try:
    df = pd.read_csv(file_name)
except FileNotFoundError:
    print(f" Error: '{file_name}' not found. Make sure train_gru.py finished successfully.")
    exit()

# 2. Set up the visual style
sns.set_theme(style="whitegrid")

fig, axes = plt.subplots(1, 3, figsize=(18, 6))
fig.suptitle('GRU Model Performance Across Preprocessing Configurations', fontsize=16, fontweight='bold', y=1.05)

# 3. Plot Training Error
sns.barplot(
    data=df, 
    x='preprocessing', 
    y='train_mse', 
    hue='preprocessing', 
    legend=False,       
    palette='Purples_d', 
    ax=axes[0]
)
axes[0].set_title('Training Error (MSE)', fontsize=14, fontweight='bold')
axes[0].set_xlabel('Preprocessing Configuration', fontsize=12)
axes[0].set_ylabel('Train MSE', fontsize=12)

# 4. Plot Testing Error 
sns.barplot(
    data=df, 
    x='preprocessing', 
    y='test_mse', 
    hue='preprocessing',
    legend=False,
    palette='Reds_d', 
    ax=axes[1]
)
axes[1].set_title('Testing Error (True Generalization)', fontsize=14, fontweight='bold')
axes[1].set_xlabel('Preprocessing Configuration', fontsize=12)
axes[1].set_ylabel('Test MSE', fontsize=12)

# 5. Plot Mean Absolute Error 
sns.barplot(
    data=df, 
    x='preprocessing', 
    y='mae', 
    hue='preprocessing',
    legend=False,
    palette='Greens_d',   
    ax=axes[2]
)
axes[2].set_title('Mean Absolute Error (MAE)', fontsize=14, fontweight='bold')
axes[2].set_xlabel('Preprocessing Configuration', fontsize=12)
axes[2].set_ylabel('Test MAE', fontsize=12)

for ax in axes:
    ax.tick_params(axis='x', rotation=45)

plt.tight_layout()
save_file = "phase1_gru_results_plot.png"
plt.savefig(save_file, dpi=300, bbox_inches='tight')
print(f"Plot saved as '{save_file}'")
plt.show()